// frontend/src/app/shell/how-built.component.ts
import { AfterViewInit, ElementRef, viewChild, ChangeDetectionStrategy, Component, computed, input, output } from '@angular/core';
import { TECH, TECH_CHIP } from './screens';

@Component({
  selector: 'app-how-built',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.Eager,
  host: { '(document:keydown.escape)': 'closed.emit()' },
  template: `
    <div style="position: fixed; inset: 0; z-index: 950; background: rgba(0,0,0,0.35); display: grid; place-items: center; padding: var(--layout-padding-large);" (click)="closed.emit()">
      <div #dialog role="dialog" aria-modal="true" aria-label="How this screen is built" tabindex="-1" (click)="$event.stopPropagation()" style="width: 34rem; max-width: 100%; max-height: 80vh; overflow-y: auto; box-sizing: border-box; background: var(--surface-color-background-white); border-radius: var(--layout-border-radius-medium); box-shadow: 0 8px 30px rgba(0,0,0,0.3); padding: var(--layout-padding-large);">
        <div style="display: flex; align-items: baseline; justify-content: space-between; gap: var(--layout-margin-small);">
          <h2 class="panel__title panel__title--inline" style="margin: 0;">How {{ tech().title }} is built</h2>
          <button type="button" (click)="closed.emit()" aria-label="Close" style="background: none; border: none; cursor: pointer; font: var(--typography-bold-body); color: var(--typography-color-secondary);">✕</button>
        </div>
        <div style="display: flex; flex-wrap: wrap; gap: 6px; margin-top: var(--layout-margin-medium);">
          @for (chip of tech().chips; track chip) {
            <span [style]="chipStyle">{{ chip }}</span>
          }
        </div>
        <p class="cell__sub" style="margin: var(--layout-margin-medium) 0 0;">{{ tech().note }}</p>
      </div>
    </div>
  `
})
export class HowBuiltComponent implements AfterViewInit {
  private dialog = viewChild.required<ElementRef<HTMLElement>>('dialog');

  // Focus moves into the dialog on open; the overlay has no focus trap, Escape and the backdrop close it.
  ngAfterViewInit() {
    this.dialog().nativeElement.focus();
  }

  screenKey = input.required<string>();
  closed = output<void>();

  readonly chipStyle = TECH_CHIP;
  tech = computed(() => TECH[this.screenKey()] ?? TECH['map']);
}

// frontend/src/shell/HowBuilt.tsx
import { useEffect, useRef, type CSSProperties } from 'react';
import { useEscapeLayer } from '../map/use-dismissable';
import { TECH, TECH_CHIP } from './screens';

const backdrop: CSSProperties = {
  position: 'fixed',
  inset: 0,
  zIndex: 950,
  background: 'rgba(0,0,0,0.35)',
  display: 'grid',
  // An `auto` track sizes to the dialog's 34rem max-content, so `max-width: 100%` below would
  // resolve against 34rem and overflow a narrow viewport. A 1fr track is the padded width.
  gridTemplateColumns: 'minmax(0, 1fr)',
  placeItems: 'center',
  padding: 'var(--layout-padding-large)',
};
const dialog: CSSProperties = {
  width: '34rem',
  maxWidth: '100%',
  overflowWrap: 'anywhere',
  maxHeight: '80vh',
  overflowY: 'auto',
  boxSizing: 'border-box',
  background: 'var(--surface-color-background-white)',
  borderRadius: 'var(--layout-border-radius-medium)',
  boxShadow: '0 8px 30px rgba(0,0,0,0.3)',
  padding: 'var(--layout-padding-large)',
};
const titleRow: CSSProperties = {
  display: 'flex',
  alignItems: 'baseline',
  justifyContent: 'space-between',
  gap: 'var(--layout-margin-small)',
};
const close: CSSProperties = {
  background: 'none',
  border: 'none',
  cursor: 'pointer',
  font: 'var(--typography-bold-body)',
  color: 'var(--typography-color-secondary)',
};
const chips: CSSProperties = {
  display: 'flex',
  flexWrap: 'wrap',
  gap: '6px',
  marginTop: 'var(--layout-margin-medium)',
};

// TECH_CHIP is one CSS declaration string, shared with every screen that lists provenance. React's
// style prop takes an object, so it is converted once here rather than written out a second time.
const chipStyle = Object.fromEntries(
  TECH_CHIP.split(';')
    .map((rule) => rule.split(':'))
    .filter(([property]) => property?.trim())
    .map(([property, ...value]) => [
      property.trim().replace(/-([a-z])/g, (_, letter: string) => letter.toUpperCase()),
      value.join(':').trim(),
    ]),
) as CSSProperties;

// The backdrop below closes on click. That is a pointer shortcut, not the only way out: Escape and
// the Close button are the keyboard routes, so the backdrop stays presentational.
/* eslint-disable jsx-a11y/click-events-have-key-events, jsx-a11y/no-noninteractive-element-interactions */

export function HowBuilt({ screenKey, onClose }: { screenKey: string; onClose: () => void }) {
  const panel = useRef<HTMLDivElement>(null);
  const tech = TECH[screenKey] ?? TECH['map'];

  // Focus moves into the dialog on open; the overlay has no focus trap, Escape and the backdrop close it.
  useEffect(() => panel.current?.focus(), []);
  useEscapeLayer(true, onClose);

  return (
    <div style={backdrop} role="presentation" onClick={onClose}>
      <div
        ref={panel}
        role="dialog"
        aria-modal="true"
        aria-label="How this screen is built"
        tabIndex={-1}
        onClick={(event) => event.stopPropagation()}
        style={dialog}
      >
        <div style={titleRow}>
          <h2 className="panel__title panel__title--inline" style={{ margin: 0 }}>
            How {tech.title} is built
          </h2>
          <button type="button" onClick={onClose} aria-label="Close" style={close}>
            ✕
          </button>
        </div>
        <div style={chips}>
          {tech.chips.map((chip) => (
            <span key={chip} style={chipStyle}>
              {chip}
            </span>
          ))}
        </div>
        <p className="cell__sub" style={{ margin: 'var(--layout-margin-medium) 0 0' }}>
          {tech.note}
        </p>
      </div>
    </div>
  );
}
