// frontend-react/src/screens/ShortLinks.tsx
import { Fragment, useState, type CSSProperties } from 'react';
import { useQueryClient } from '@tanstack/react-query';
import {
  LINKS_QUERY,
  createLink,
  isMine,
  removeLink,
  repointLink,
  useLinks,
  type ShortLink,
} from '../api/links';
import { getSessionClaims } from '../api/keycloak';
import { errorMessage } from '../api/client';
import { linkButton, primaryButton, stack, textInput } from './controls';
import { dayMonth } from '../dates';

const SKELETON_ROWS = [1, 2, 3, 4];

const cancelButton: CSSProperties = { ...linkButton, color: 'var(--typography-color-secondary)' };

/** The narrower input a row swaps in while its destination is being repointed. */
const editInput: CSSProperties = {
  width: '100%',
  boxSizing: 'border-box',
  padding: '0.35rem 0.6rem',
  border: 'var(--layout-border-width-small) solid var(--surface-color-border-default)',
  borderRadius: 'var(--layout-border-radius-small)',
  font: 'var(--typography-regular-small-body)',
};

/** Mine first, then everyone's. Empty groups are dropped rather than shown as a bare heading. */
function linkGroups(links: ShortLink[], me: string): { title: string; rows: ShortLink[] }[] {
  const mine = links.filter((link) => isMine(link, me));
  const shared = links.filter((link) => !mine.includes(link));
  return [
    { title: 'My links', rows: mine },
    { title: 'Shared links', rows: shared },
  ].filter((group) => group.rows.length > 0);
}

export function ShortLinks() {
  const queryClient = useQueryClient();
  const query = useLinks();

  const links = query.data ?? [];
  const loading = query.isFetching;
  const groups = linkGroups(links, getSessionClaims()?.preferredUsername ?? '');

  const [error, setError] = useState('');
  const [formOpen, setFormOpen] = useState(false);
  const [newUrl, setNewUrl] = useState('');
  const [newCode, setNewCode] = useState('');
  const [newNote, setNewNote] = useState('');
  const [newPersonal, setNewPersonal] = useState(false);

  /** Code of the row being repointed, '' when none. */
  const [editingCode, setEditingCode] = useState('');
  const [editUrl, setEditUrl] = useState('');

  /** The row the clipboard last answered for, and what it said. */
  const [copy, setCopy] = useState<{ code: string; ok: boolean } | null>(null);

  /** The read failure already dismissed, so a later one is shown again rather than swallowed. */
  const [dismissedRead, setDismissedRead] = useState<unknown>(null);

  const readError = query.error && query.error !== dismissedRead ? errorMessage(query.error) : '';
  const shown = error || readError;

  const reload = () => queryClient.invalidateQueries({ queryKey: LINKS_QUERY });

  async function write(send: () => Promise<unknown>): Promise<boolean> {
    setError('');
    try {
      await send();
      await reload();
      return true;
    } catch (err) {
      setError(errorMessage(err));
      return false;
    }
  }

  /** Opening or closing the form clears the callout, whichever read or write put it there. */
  function toggleForm() {
    setFormOpen(!formOpen);
    setError('');
    setDismissedRead(query.error ?? null);
  }

  async function submit() {
    const url = newUrl.trim();
    if (!url) return;
    const created = await write(() => createLink(url, newNote.trim(), newCode.trim(), newPersonal));
    if (!created) return;
    setNewUrl('');
    setNewCode('');
    setNewNote('');
    setNewPersonal(false);
    setFormOpen(false);
  }

  function startRepoint(link: ShortLink) {
    setEditingCode(link.id);
    setEditUrl(link.url);
    setError('');
  }

  async function saveRepoint(code: string) {
    const url = editUrl.trim();
    if (!url) return;
    if (await write(() => repointLink(code, url))) setEditingCode('');
  }

  async function remove(link: ShortLink) {
    if (!confirm(`Delete ${link.shortUrl}? Anything already printed with this link stops working.`)) return;
    await write(() => removeLink(link.id));
  }

  async function copyLink(link: ShortLink) {
    try {
      await navigator.clipboard.writeText(link.shortUrl);
      setCopy({ code: link.id, ok: true });
    } catch {
      // Clipboard refused (no permission, or an insecure context). The short URL is still on screen.
      setCopy({ code: link.id, ok: false });
    }
  }

  return (
    <>
      <div className="screen-header">
        <div className="screen-header__text">
          <h1>Short URLs</h1>
          <p>Permanent links DEMI issues for posters, campaigns and staff sharing.</p>
        </div>
        <button type="button" onClick={toggleForm} style={primaryButton}>
          {formOpen ? 'Cancel' : 'New short link'}
        </button>
      </div>

      {shown && <div className="callout callout--warning">{shown}</div>}

      {formOpen && (
        <section className="panel panel--padded">
          <h2 className="panel__title panel__title--inline">New short link</h2>
          <div style={{ ...stack, marginTop: 'var(--layout-margin-medium)' }}>
            <label style={{ display: 'block' }}>
              <span className="micro-label">Destination</span>
              <input
                type="url"
                placeholder="https://projects.eao.gov.bc.ca/…"
                value={newUrl}
                onChange={(event) => setNewUrl(event.target.value)}
                style={textInput}
              />
            </label>
            <label style={{ display: 'block' }}>
              <span className="micro-label">Custom code, optional</span>
              <input
                type="text"
                placeholder="site-c-eac"
                value={newCode}
                onChange={(event) => setNewCode(event.target.value)}
                style={textInput}
              />
              <span className="cell__sub">
                3–64 characters of a–z, 0–9, hyphen or underscore. Left blank, DEMI generates one.
              </span>
            </label>
            <label style={{ display: 'block' }}>
              <span className="micro-label">Note</span>
              <input
                type="text"
                placeholder="Where this link is being used"
                value={newNote}
                onChange={(event) => setNewNote(event.target.value)}
                style={textInput}
              />
            </label>
            <div>
              <label
                style={{
                  display: 'flex',
                  alignItems: 'center',
                  gap: '0.5rem',
                  font: 'var(--typography-regular-body)',
                  cursor: 'pointer',
                }}
              >
                <input type="checkbox" checked={newPersonal} onChange={() => setNewPersonal(!newPersonal)} />
                Personal (only visible to me)
              </label>
              <span className="cell__sub">Anyone with the short URL can still open it.</span>
            </div>
          </div>
          <div className="panel__actions">
            <button type="button" disabled={!newUrl.trim()} onClick={() => void submit()} style={primaryButton}>
              Create link
            </button>
          </div>
        </section>
      )}

      <section
        className="panel panel--scroll"
        aria-busy={loading ? 'true' : undefined}
        style={{ opacity: loading && links.length ? 0.6 : undefined }}
      >
        {loading && !links.length && <p className="visually-hidden">Loading short links…</p>}
        <table style={{ minWidth: '52rem', tableLayout: 'fixed', width: '100%' }}>
          <thead>
            <tr>
              <th style={{ width: '15rem' }}>Short link</th>
              <th style={{ width: '15rem' }}>Destination</th>
              <th style={{ width: '13rem' }}>Note</th>
              <th style={{ width: '7rem' }}>Created by</th>
              <th style={{ width: '5.5rem' }}>Created</th>
              <th style={{ width: '10rem', textAlign: 'right' }} />
            </tr>
          </thead>
          <tbody>
            {groups.map((group) => (
              <Fragment key={group.title}>
                <tr>
                  <th
                    colSpan={6}
                    scope="colgroup"
                    className="micro-label"
                    style={{ textAlign: 'left', background: 'var(--surface-color-background-light-gray)' }}
                  >
                    {group.title}
                  </th>
                </tr>
                {group.rows.map((link) => (
                  <tr key={link.id}>
                    <td>
                      <a href={link.shortUrl} target="_blank" rel="noopener noreferrer">
                        <code className="cell__mono" style={{ overflowWrap: 'anywhere', color: 'inherit' }}>
                          {link.shortUrl}
                        </code>
                      </a>
                      {link.personal && (
                        <span className="pill pill--info" style={{ marginLeft: '0.35rem' }}>
                          Personal
                        </span>
                      )}
                    </td>
                    <td className="cell--truncate cell--muted">
                      {editingCode === link.id ? (
                        <input
                          type="url"
                          aria-label="New destination"
                          value={editUrl}
                          onChange={(event) => setEditUrl(event.target.value)}
                          style={editInput}
                        />
                      ) : (
                        link.url
                      )}
                    </td>
                    <td>{link.note || '—'}</td>
                    <td className="cell--muted">{link.createdBy}</td>
                    <td className="cell--muted cell--nowrap">{dayMonth(link.createdAt) || '—'}</td>
                    <td className="cell--right cell--nowrap">
                      <span className="row-actions">
                        {editingCode === link.id ? (
                          <>
                            <button type="button" onClick={() => void saveRepoint(link.id)} style={linkButton}>
                              Save
                            </button>
                            <button type="button" onClick={() => setEditingCode('')} style={cancelButton}>
                              Cancel
                            </button>
                          </>
                        ) : (
                          <>
                            <button type="button" onClick={() => void copyLink(link)} style={linkButton}>
                              {copy?.code === link.id ? (copy.ok ? 'Copied' : 'Copy failed') : 'Copy'}
                            </button>
                            <button type="button" onClick={() => startRepoint(link)} style={linkButton}>
                              Repoint
                            </button>
                            <button type="button" onClick={() => void remove(link)} style={linkButton}>
                              Delete
                            </button>
                          </>
                        )}
                      </span>
                    </td>
                  </tr>
                ))}
              </Fragment>
            ))}
            {!groups.length &&
              (loading ? (
                SKELETON_ROWS.map((row) => (
                  <tr key={row} aria-hidden="true">
                    <td>
                      <span className="skeleton skeleton--text" style={{ width: '90%' }} />
                    </td>
                    <td>
                      <span className="skeleton skeleton--text" style={{ width: '85%' }} />
                    </td>
                    <td>
                      <span className="skeleton skeleton--text" style={{ width: '70%' }} />
                    </td>
                    <td>
                      <span className="skeleton skeleton--text" style={{ width: '60%' }} />
                    </td>
                    <td>
                      <span className="skeleton skeleton--text" style={{ width: '3rem' }} />
                    </td>
                    <td className="cell--right">
                      <span className="skeleton skeleton--text" style={{ width: '6rem' }} />
                    </td>
                  </tr>
                ))
              ) : (
                <tr>
                  <td colSpan={6} className="cell--muted">
                    No short links yet.
                  </td>
                </tr>
              ))}
          </tbody>
        </table>
      </section>

      <p className="footnote">
        Short links are permanent and redirect without caching, so a repointed link takes effect on the next click
        — including on links already printed. Deleting one is not reversible; the audit trail keeps the record.
      </p>
    </>
  );
}

// frontend/src/app/components/short-links/short-links.component.ts
import { ChangeDetectionStrategy, Component, OnInit, computed, inject, signal } from '@angular/core';
import { LinksService, ShortLink, isMine } from '../../services/links.service';
import { RegistryStateService } from '../../services/registry-state.service';

@Component({
  selector: 'app-short-links',
  standalone: true,
  imports: [],
  templateUrl: './short-links.component.html',
  changeDetection: ChangeDetectionStrategy.Eager,
  styleUrls: []
})
export class ShortLinksComponent implements OnInit {
  links = inject(LinksService);
  private registry = inject(RegistryStateService);

  formOpen = signal(false);
  newUrl = signal('');
  newCode = signal('');
  newNote = signal('');
  newPersonal = signal(false);

  private me = computed(() =>
    this.registry.isAuthenticated() ? this.registry.keycloak?.tokenParsed?.preferred_username || '' : ''
  );

  /** Mine first, then everyone's. Empty groups are dropped rather than shown as a bare heading. */
  linkGroups = computed<{ title: string; rows: ShortLink[] }[]>(() => {
    const me = this.me();
    const mine = this.links.links().filter(l => isMine(l, me));
    const shared = this.links.links().filter(l => !mine.includes(l));
    return [
      { title: 'My links', rows: mine },
      { title: 'Shared links', rows: shared }
    ].filter(g => g.rows.length > 0);
  });

  /** Code of the row being repointed, '' when none. */
  editingCode = signal('');
  editUrl = signal('');

  /** Code whose short URL was last copied, so the row can confirm it. */
  copiedCode = signal('');

  ngOnInit() {
    this.links.load();
  }

  value(event: Event): string {
    return (event.target as HTMLInputElement).value;
  }

  /** ISO timestamp to the spec's "24 Aug". */
  shortDate(iso: string): string {
    const d = new Date(iso);
    return isNaN(d.getTime()) ? '—' : d.toLocaleDateString('en-CA', { day: '2-digit', month: 'short' });
  }

  toggleForm() {
    this.formOpen.update(open => !open);
    this.links.error.set('');
  }

  async submit() {
    const url = this.newUrl().trim();
    if (!url) return;
    const created = await this.links.create(url, this.newNote().trim(), this.newCode().trim(), this.newPersonal());
    if (!created) return;
    this.newUrl.set('');
    this.newCode.set('');
    this.newNote.set('');
    this.newPersonal.set(false);
    this.formOpen.set(false);
  }

  startRepoint(link: ShortLink) {
    this.editingCode.set(link.id);
    this.editUrl.set(link.url);
    this.links.error.set('');
  }

  cancelRepoint() {
    this.editingCode.set('');
  }

  async saveRepoint(code: string) {
    const url = this.editUrl().trim();
    if (!url) return;
    if (await this.links.repoint(code, url)) this.editingCode.set('');
  }

  async remove(link: ShortLink) {
    if (!confirm(`Delete ${link.shortUrl}? Anything already printed with this link stops working.`)) return;
    await this.links.remove(link.id);
  }

  async copy(link: ShortLink) {
    await navigator.clipboard.writeText(link.shortUrl);
    this.copiedCode.set(link.id);
  }
}

<div class="screen-header">
  <div class="screen-header__text">
    <h1>Short URLs</h1>
    <p>Permanent links DEMI issues for posters, campaigns and staff sharing.</p>
  </div>
  <button type="button" (click)="toggleForm()" style="background: var(--surface-color-primary-default); color: var(--surface-color-background-white); border: none; border-radius: var(--layout-border-radius-small); padding: 0.55rem 1.1rem; font: var(--typography-bold-small-body); cursor: pointer;">{{ formOpen() ? 'Cancel' : 'New short link' }}</button>
</div>

@if (links.error()) {
  <div class="callout callout--warning">{{ links.error() }}</div>
}

@if (formOpen()) {
  <section class="panel panel--padded">
    <h2 class="panel__title panel__title--inline">New short link</h2>
    <div style="display: flex; flex-direction: column; gap: var(--layout-margin-medium); margin-top: var(--layout-margin-medium);">
      <label style="display: block;">
        <span class="micro-label">Destination</span>
        <input type="url" placeholder="https://projects.eao.gov.bc.ca/…" [value]="newUrl()" (input)="newUrl.set(value($event))" style="width: 100%; box-sizing: border-box; padding: 0.5rem 0.7rem; border: var(--layout-border-width-small) solid var(--surface-color-border-default); border-radius: var(--layout-border-radius-small); font: var(--typography-regular-body);">
      </label>
      <label style="display: block;">
        <span class="micro-label">Custom code, optional</span>
        <input type="text" placeholder="site-c-eac" [value]="newCode()" (input)="newCode.set(value($event))" style="width: 100%; box-sizing: border-box; padding: 0.5rem 0.7rem; border: var(--layout-border-width-small) solid var(--surface-color-border-default); border-radius: var(--layout-border-radius-small); font: var(--typography-regular-body);">
        <span class="cell__sub">3–64 characters of a–z, 0–9, hyphen or underscore. Left blank, DEMI generates one.</span>
      </label>
      <label style="display: block;">
        <span class="micro-label">Note</span>
        <input type="text" placeholder="Where this link is being used" [value]="newNote()" (input)="newNote.set(value($event))" style="width: 100%; box-sizing: border-box; padding: 0.5rem 0.7rem; border: var(--layout-border-width-small) solid var(--surface-color-border-default); border-radius: var(--layout-border-radius-small); font: var(--typography-regular-body);">
      </label>
      <div>
        <label style="display: flex; align-items: center; gap: 0.5rem; font: var(--typography-regular-body); cursor: pointer;">
          <input type="checkbox" [checked]="newPersonal()" (change)="newPersonal.set(!newPersonal())">
          Personal (only visible to me)
        </label>
        <span class="cell__sub">Anyone with the short URL can still open it.</span>
      </div>
    </div>
    <div class="panel__actions">
      <button type="button" [disabled]="!newUrl().trim()" (click)="submit()" style="background: var(--surface-color-primary-default); color: var(--surface-color-background-white); border: none; border-radius: var(--layout-border-radius-small); padding: 0.55rem 1.1rem; font: var(--typography-bold-small-body); cursor: pointer;">Create link</button>
    </div>
  </section>
}

<section class="panel panel--scroll" [attr.aria-busy]="links.loading() ? 'true' : null" [style.opacity]="links.loading() && links.links().length ? 0.6 : null">
  @if (links.loading() && !links.links().length) {
    <p class="visually-hidden">Loading short links…</p>
  }
  <table style="min-width: 52rem; table-layout: fixed; width: 100%;">
    <thead>
      <tr>
        <th style="width: 15rem;">Short link</th>
        <th style="width: 15rem;">Destination</th>
        <th style="width: 13rem;">Note</th>
        <th style="width: 7rem;">Created by</th>
        <th style="width: 5.5rem;">Created</th>
        <th style="width: 10rem; text-align: right;"></th>
      </tr>
    </thead>
    <tbody>
      @for (group of linkGroups(); track group.title) {
        <tr>
          <th colspan="6" scope="colgroup" class="micro-label" style="text-align: left; background: var(--surface-color-background-light-gray);">{{ group.title }}</th>
        </tr>
        @for (link of group.rows; track link.id) {
        <tr>
          <td>
            <a [href]="link.shortUrl" target="_blank" rel="noopener"><code class="cell__mono" style="overflow-wrap: anywhere; color: inherit;">{{ link.shortUrl }}</code></a>
            @if (link.personal) {
              <span class="pill pill--info" style="margin-left: 0.35rem;">Personal</span>
            }
          </td>
          <td class="cell--truncate cell--muted">
            @if (editingCode() === link.id) {
              <input type="url" aria-label="New destination" [value]="editUrl()" (input)="editUrl.set(value($event))" style="width: 100%; box-sizing: border-box; padding: 0.35rem 0.6rem; border: var(--layout-border-width-small) solid var(--surface-color-border-default); border-radius: var(--layout-border-radius-small); font: var(--typography-regular-small-body);">
            } @else {
              {{ link.url }}
            }
          </td>
          <td>{{ link.note || '—' }}</td>
          <td class="cell--muted">{{ link.createdBy }}</td>
          <td class="cell--muted cell--nowrap">{{ shortDate(link.createdAt) }}</td>
          <td class="cell--right cell--nowrap">
            <span class="row-actions">
              @if (editingCode() === link.id) {
                <button type="button" (click)="saveRepoint(link.id)" style="background: none; border: none; padding: 0; font: var(--typography-regular-small-body); color: var(--surface-color-primary-default); text-decoration: underline; cursor: pointer;">Save</button>
                <button type="button" (click)="cancelRepoint()" style="background: none; border: none; padding: 0; font: var(--typography-regular-small-body); color: var(--typography-color-secondary); text-decoration: underline; cursor: pointer;">Cancel</button>
              } @else {
                <button type="button" (click)="copy(link)" style="background: none; border: none; padding: 0; font: var(--typography-regular-small-body); color: var(--surface-color-primary-default); text-decoration: underline; cursor: pointer;">{{ copiedCode() === link.id ? 'Copied' : 'Copy' }}</button>
                <button type="button" (click)="startRepoint(link)" style="background: none; border: none; padding: 0; font: var(--typography-regular-small-body); color: var(--surface-color-primary-default); text-decoration: underline; cursor: pointer;">Repoint</button>
                <button type="button" (click)="remove(link)" style="background: none; border: none; padding: 0; font: var(--typography-regular-small-body); color: var(--surface-color-primary-default); text-decoration: underline; cursor: pointer;">Delete</button>
              }
            </span>
          </td>
        </tr>
        }
      } @empty {
        @if (links.loading()) {
          @for (i of [1, 2, 3, 4]; track i) {
            <tr aria-hidden="true">
              <td><span class="skeleton skeleton--text" style="width: 90%;"></span></td>
              <td><span class="skeleton skeleton--text" style="width: 85%;"></span></td>
              <td><span class="skeleton skeleton--text" style="width: 70%;"></span></td>
              <td><span class="skeleton skeleton--text" style="width: 60%;"></span></td>
              <td><span class="skeleton skeleton--text" style="width: 3rem;"></span></td>
              <td class="cell--right"><span class="skeleton skeleton--text" style="width: 6rem;"></span></td>
            </tr>
          }
        } @else {
          <tr>
            <td colspan="6" class="cell--muted">No short links yet.</td>
          </tr>
        }
      }
    </tbody>
  </table>
</section>

<p class="footnote">Short links are permanent and redirect without caching, so a repointed link takes effect on the next click — including on links already printed. Deleting one is not reversible; the audit trail keeps the record.</p>
