// frontend/src/app/components/api-docs/api-docs.component.ts
import { ChangeDetectionStrategy, Component, inject } from '@angular/core';
import { ConfigService } from '../../services/config.service';

/** Environments that serve the Swagger UI. Anywhere else the route is not published. */
const SWAGGER_ENVIRONMENTS = ['dev', 'test'];

@Component({
  selector: 'app-api-docs',
  standalone: true,
  imports: [],
  templateUrl: './api-docs.component.html',
  changeDetection: ChangeDetectionStrategy.Eager,
  styleUrls: []
})
export class ApiDocsComponent {
  private configService = inject(ConfigService);

  get swaggerAvailable(): boolean {
    return SWAGGER_ENVIRONMENTS.includes(String(this.configService.config.ENVIRONMENT || '').toLowerCase());
  }

  /** The spec is a route under the API base: /api/api-docs works relative and absolute. */
  openSwagger() {
    const basePath = this.configService.config.API_PATH || '/api';
    window.open(`${basePath}/api-docs`, '_blank');
  }
}

<div class="screen-header">
  <div class="screen-header__text">
    <h1>API documentation</h1>
    <p>The Swagger UI the API serves itself, plus what a caller needs before the first request.</p>
  </div>
  @if (swaggerAvailable) {
    <button type="button" (click)="openSwagger()" style="background: var(--surface-color-primary-default); color: var(--surface-color-background-white); border: none; border-radius: var(--layout-border-radius-small); padding: 0.55rem 1.1rem; font: var(--typography-bold-small-body); cursor: pointer;">Open Swagger UI</button>
  }
</div>

<section class="panel panel--padded">
  <h2 class="panel__title panel__title--inline">Authenticating</h2>
  <div style="display: flex; flex-direction: column; gap: var(--layout-margin-medium);">
    <div>
      <div class="cell__title">Staff and applications</div>
      <div class="cell__sub" style="overflow-wrap: anywhere;">Keycloak realm <code class="cell__mono">eao-epic</code>. Applications use a service account — <code class="cell__mono">client_credentials</code>, then a normal bearer token.</div>
    </div>
    <div>
      <div class="cell__title">Callers without a Keycloak client</div>
      <div class="cell__sub" style="overflow-wrap: anywhere;">A registry API key: <code class="cell__mono">X-Api-Key: demi_&lt;env&gt;_&lt;keyId&gt;_&lt;secret&gt;</code>, issued with its own roles, expiry and revocation.</div>
    </div>
  </div>
</section>

<section class="panel panel--scroll">
  <h2 class="panel__title">Roles</h2>
  <table style="min-width: 40rem;">
    <thead>
      <tr>
        <th>Role</th>
        <th>Reads</th>
        <th style="width: 8rem;">Writes data</th>
        <th style="width: 9rem;">Admin routes</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><span class="role-chip">public</span></td>
        <td class="cell--muted">published rows only</td>
        <td class="cell--muted">no</td>
        <td class="cell--muted">no</td>
      </tr>
      <tr>
        <td><span class="role-chip">compliance</span></td>
        <td class="cell--muted">sealed rows, on /api/sealed only</td>
        <td class="cell--muted">no</td>
        <td class="cell--muted">no</td>
      </tr>
      <tr>
        <td><span class="role-chip">demi-service-read</span></td>
        <td class="cell--muted">everything the ACL allows</td>
        <td class="cell--muted">no</td>
        <td class="cell--muted">no</td>
      </tr>
      <tr>
        <td><span class="role-chip">demi-service-write</span></td>
        <td class="cell--muted">everything the ACL allows</td>
        <td class="cell--muted">yes</td>
        <td class="cell--muted">no</td>
      </tr>
      <tr>
        <td>
          <span class="role-chips">
            <span class="role-chip">sysadmin</span>
            <span class="role-chip">staff</span>
            <span class="role-chip">demi-admin</span>
          </span>
        </td>
        <td class="cell--muted">everything the ACL allows</td>
        <td class="cell--muted">yes</td>
        <td class="cell--muted">yes</td>
      </tr>
      <tr>
        <td><span class="role-chip">project:&lt;id&gt;</span></td>
        <td class="cell--muted">scope, not a privilege — narrows any role to those projects</td>
        <td class="cell--muted">no</td>
        <td class="cell--muted">no</td>
      </tr>
    </tbody>
  </table>
</section>

<p class="footnote">
  Ask for the least privilege that works. A privileged credential carrying a project scope is privileged within those projects only.
  @if (!swaggerAvailable) {
    Swagger UI is not linked here: the API serves it on dev and test only, so there is nothing to open in this environment.
  }
</p>

// frontend/src/screens/ApiDocs.tsx
import { config } from '../config';
import { apiDocsTarget } from '../routes';
import { primaryButton, stack } from './controls';

/** Environments that serve the Swagger UI. Anywhere else the route is not published. */
const SWAGGER_ENVIRONMENTS = ['dev', 'test'];

export function ApiDocs() {
  const swaggerAvailable = SWAGGER_ENVIRONMENTS.includes(String(config().ENVIRONMENT || '').toLowerCase());

  // `noopener` as well as `_blank`: without it the spec page is handed a handle on this window.
  const openSwagger = () => window.open(apiDocsTarget(config().API_PATH), '_blank', 'noopener');

  return (
    <>
      <div className="screen-header">
        <div className="screen-header__text">
          <h1>API documentation</h1>
          <p>The Swagger UI the API serves itself, plus what a caller needs before the first request.</p>
        </div>
        {swaggerAvailable && (
          <button type="button" onClick={openSwagger} style={primaryButton}>
            Open Swagger UI
          </button>
        )}
      </div>

      <section className="panel panel--padded">
        <h2 className="panel__title panel__title--inline">Authenticating</h2>
        <div style={stack}>
          <div>
            <div className="cell__title">Staff and applications</div>
            <div className="cell__sub" style={{ overflowWrap: 'anywhere' }}>
              Keycloak realm <code className="cell__mono">eao-epic</code>. Applications use a service account —{' '}
              <code className="cell__mono">client_credentials</code>, then a normal bearer token.
            </div>
          </div>
          <div>
            <div className="cell__title">Callers without a Keycloak client</div>
            <div className="cell__sub" style={{ overflowWrap: 'anywhere' }}>
              A registry API key: <code className="cell__mono">{'X-Api-Key: demi_<env>_<keyId>_<secret>'}</code>,
              issued with its own roles, expiry and revocation.
            </div>
          </div>
        </div>
      </section>

      <section className="panel panel--scroll">
        <h2 className="panel__title">Roles</h2>
        <table style={{ minWidth: '40rem' }}>
          <thead>
            <tr>
              <th>Role</th>
              <th>Reads</th>
              <th style={{ width: '8rem' }}>Writes data</th>
              <th style={{ width: '9rem' }}>Admin routes</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>
                <span className="role-chip">public</span>
              </td>
              <td className="cell--muted">published rows only</td>
              <td className="cell--muted">no</td>
              <td className="cell--muted">no</td>
            </tr>
            <tr>
              <td>
                <span className="role-chip">compliance</span>
              </td>
              <td className="cell--muted">sealed rows, on /api/sealed only</td>
              <td className="cell--muted">no</td>
              <td className="cell--muted">no</td>
            </tr>
            <tr>
              <td>
                <span className="role-chip">demi-service-read</span>
              </td>
              <td className="cell--muted">everything the ACL allows</td>
              <td className="cell--muted">no</td>
              <td className="cell--muted">no</td>
            </tr>
            <tr>
              <td>
                <span className="role-chip">demi-service-write</span>
              </td>
              <td className="cell--muted">everything the ACL allows</td>
              <td className="cell--muted">yes</td>
              <td className="cell--muted">no</td>
            </tr>
            <tr>
              <td>
                <span className="role-chips">
                  <span className="role-chip">sysadmin</span>
                  <span className="role-chip">staff</span>
                  <span className="role-chip">demi-admin</span>
                </span>
              </td>
              <td className="cell--muted">everything the ACL allows</td>
              <td className="cell--muted">yes</td>
              <td className="cell--muted">yes</td>
            </tr>
            <tr>
              <td>
                <span className="role-chip">{'project:<id>'}</span>
              </td>
              <td className="cell--muted">scope, not a privilege — narrows any role to those projects</td>
              <td className="cell--muted">no</td>
              <td className="cell--muted">no</td>
            </tr>
          </tbody>
        </table>
      </section>

      <p className="footnote">
        Ask for the least privilege that works. A privileged credential carrying a project scope is privileged within
        those projects only.
        {!swaggerAvailable &&
          ' Swagger UI is not linked here: the API serves it on dev and test only, so there is nothing to open in this environment.'}
      </p>
    </>
  );
}
